<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\SatelliteData.Application\SatelliteData.Application.csproj" />
    <ProjectReference Include="..\SatelliteData.Infrastructure\SatelliteData.Infrastructure.csproj" />
    <ProjectReference Include="..\SatelliteData.Domain\SatelliteData.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.7" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
